# src/localization.py

STRINGS = {
    "es": {
        "title": "Paleta de Tiles",
        "save_btn": "💾 Salvar",
        "open_btn": "📂 Abrir",
        "category": "Categoría:",
        "elements": "Elementos:",
        "no_assets": "No hay assets en assets/",
        "hint_config": "[ENTER]: Configurar",
        "hint_shortcuts": "F5: Exportar | F6: Importar",
        "modal_title": "Propiedades del Documento",
        "modal_grid": "Tamaño de Rejilla:",
        "modal_width": "Ancho del Mapa:",
        "modal_height": "Alto del Mapa:",
        "modal_accept": "Aceptar",
        "modal_cancel": "Cancelar",
        "modal_res": "Resolución:",
        "hint_mirror": "[ALT]: Espejo Horizontal",
        "hint_player": "[CTRL + Click]: Inicio Jugador",
        "player_marker": "JUGADOR",
        "hud_mirrored": "Espejo: ACTIVO"
    },
    "en": {
        "title": "Tile Palette",
        "save_btn": "💾 Save",
        "open_btn": "📂 Open",
        "category": "Category:",
        "elements": "Elements:",
        "no_assets": "No assets in assets/",
        "hint_config": "[ENTER]: Settings",
        "hint_shortcuts": "F5: Export | F6: Import",
        "modal_title": "Document Properties",
        "modal_grid": "Grid Size:",
        "modal_width": "Map Width:",
        "modal_height": "Map Height:",
        "modal_accept": "Accept",
        "modal_cancel": "Cancel",
        "modal_res": "Resolution:",
        "hint_mirror": "[ALT]: Flip Horizontal",
        "hint_player": "[CTRL + Click]: Player Spawn",
        "player_marker": "PLAYER",
        "hud_mirrored": "Flip: ACTIVE"
    },
    "fr": {
        "title": "Palette de Tuiles",
        "save_btn": "💾 Sauver",
        "open_btn": "📂 Ouvrir",
        "category": "Catégorie:",
        "elements": "Éléments:",
        "no_assets": "Pas d'actifs dans assets/",
        "hint_config": "[ENTER]: Configurer",
        "hint_shortcuts": "F5: Exporter | F6: Importer",
        "modal_title": "Propriétés du Document",
        "modal_grid": "Taille de Grille:",
        "modal_width": "Largeur du Map:",
        "modal_height": "Hauteur du Map:",
        "modal_accept": "Accepter",
        "modal_cancel": "Annuler",
        "modal_res": "Résolution:",
        "hint_mirror": "[ALT]: Miroir Horizontal",
        "hint_player": "[CTRL + Click]: Départ Joueur",
        "player_marker": "JOUEUR",
        "hud_mirrored": "Miroir: ACTIF"
    },
    "de": {
        "title": "Kachelpalette",
        "save_btn": "💾 Speichern",
        "open_btn": "📂 Öffnen",
        "category": "Kategorie:",
        "elements": "Elemente:",
        "no_assets": "Keine Assets in assets/",
        "hint_config": "[ENTER]: Einstellen",
        "hint_shortcuts": "F5: Exportieren | F6: Importieren",
        "modal_title": "Dokumenteigenschaften",
        "modal_grid": "Rastergröße:",
        "modal_width": "Kartenbreite:",
        "modal_height": "Kartenhöhe:",
        "modal_accept": "Akzeptieren",
        "modal_cancel": "Abbrechen",
        "modal_res": "Auflösung:",
        "hint_mirror": "[ALT]: Horizontal Spiegeln",
        "hint_player": "[CTRL + Click]: Spieler-Spawn",
        "player_marker": "SPIELER",
        "hud_mirrored": "Spiegel: AKTIV"
    },
    "pt": {
        "title": "Paleta de Tiles",
        "save_btn": "💾 Salvar",
        "open_btn": "📂 Abrir",
        "category": "Categoria:",
        "elements": "Elementos:",
        "no_assets": "Sem assets em assets/",
        "hint_config": "[ENTER]: Configurar",
        "hint_shortcuts": "F5: Exportar | F6: Importar",
        "modal_title": "Propriedades do Documento",
        "modal_grid": "Tamanho da Grade:",
        "modal_width": "Largura do Mapa:",
        "modal_height": "Altura do Mapa:",
        "modal_accept": "Aceitar",
        "modal_cancel": "Cancelar",
        "modal_res": "Resolução:",
        "hint_mirror": "[ALT]: Espelhar Horizontal",
        "hint_player": "[CTRL + Click]: Início Jogador",
        "player_marker": "JOGADOR",
        "hud_mirrored": "Espelho: ATIVO"
    },
    "it": {
        "title": "Tavolozza Tile",
        "save_btn": "💾 Salva",
        "open_btn": "📂 Apri",
        "category": "Categoria:",
        "elements": "Elementi:",
        "no_assets": "Nessun asset in assets/",
        "hint_config": "[ENTER]: Configura",
        "hint_shortcuts": "F5: Esporta | F6: Importa",
        "modal_title": "Proprietà del Documento",
        "modal_grid": "Dimensione Griglia:",
        "modal_width": "Larghezza Mappa:",
        "modal_height": "Altezza Mappa:",
        "modal_accept": "Accetta",
        "modal_cancel": "Annulla",
        "modal_res": "Risoluzione:",
        "hint_mirror": "[ALT]: Specchia Orizzontale",
        "hint_player": "[CTRL + Click]: Spawn Giocatore",
        "player_marker": "GIOCATORE",
        "hud_mirrored": "Specchio: ATTIVO"
    }
}

def tr(key):
    """Función rápida para obtener el texto traducido según el idioma actual."""
    from src.config import current_cfg
    lang = current_cfg.language
    # Si por algún motivo no encuentra la clave, devuelve el texto en inglés por seguridad
    return STRINGS.get(lang, STRINGS["en"]).get(key, f"[{key}]")
